### ISSUE TITLE
Kernel64Patcher fails while writing out patched file

### ISSUE THREAD

**Issue by M1staAwesome** [Ralph0045/Kernel64Patcher#1]
While trying to patch an iOS 13.4 iPhone9,3 kernelcache, Kernel64Patcher returns this:
main: Starting...
got fat macho with first slice at 63488000
Detected non-slid kernel.
Inited offsetfinder64 119 bb85f68844565c1c774027261ea455efb37b4862

Kernel: Adding AMFI_get_out_of_my_way patch...
get_AMFI_13_patch: Entering ...
get_AMFI_13_patch: Found Entitlements are too small str loc at 0xfffffff0056009fa
get_AMFI_13_patch: Found Entitlements are too small str ref loc at 0xfffffff005efef5c
get_AMFI_13_patch: Patching AMFI at 0xfffffff005efd8e8
get_AMFI_13_patch: Leaving...
applying patch=0xfffffff005efd8e8 : e0030032c0035fd6
main: Writing out patched file to kernelpwn...
[1]    16499 segmentation fault  kernel64patcher kernel kernelpwn 13 -a.

The kernel was extracted from img4lib using this command: `img4 -i kernelcache.release.iphone9 -o kernel.raw`.

**Comment by RedL0tus** [comment]
Met the same problem with kernelcache for ipad7b (`kernelcache.release.ipad7b`), while the program works perfectly for ipad6f's kernel (extracted from` iPad_64bit_TouchID_ASTC_13.4.1_17E262_Restore.ipsw`, sha512sum `67cd3807bd5e404e00c0de1e07f7b9e5eb4708a55c6421faa84a9a8e2162bafb95c2c6410b1f34299998785c59f9e9ebe746cfaf84ad289c0cd4bc60e80c4cb7`).

Here are some sweet stack traces:

```
(lldb) target create "/usr/local/bin/Kernel64Patcher"
Current executable set to '/usr/local/bin/Kernel64Patcher' (x86_64).
(lldb) settings set -- target.run-args  "kcache-try.raw" "kcache-try.patched" "13" "-a"
(lldb) r
Process 94654 launched: '/usr/local/bin/Kernel64Patcher' (x86_64)
main: Starting...
got fat macho with first slice at 40013824
Detected non-slid kernel.
Inited offsetfinder64 119 bb85f68844565c1c774027261ea455efb37b4862

Kernel: Adding AMFI_get_out_of_my_way patch...
get_AMFI_13_patch: Entering ...
get_AMFI_13_patch: Found Entitlements are too small str loc at 0xfffffff0055849fa
get_AMFI_13_patch: Found Entitlements are too small str ref loc at 0xfffffff005e82f5c
get_AMFI_13_patch: Patching AMFI at 0xfffffff005e818e8
get_AMFI_13_patch: Leaving...
applying patch=0xfffffff005e818e8 : e0030032c0035fd6
main: Writing out patched file to kcache-try.patched...
Process 94654 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10645100c)
    frame #0: 0x00007fff6abd794d libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 77
libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell:
->  0x7fff6abd794d <+77>: vmovups -0x10(%rsi,%rdx), %xmm1
    0x7fff6abd7953 <+83>: subq   $0x20, %rdx
    0x7fff6abd7957 <+87>: jbe    0x7fff6abd7983            ; <+131>
    0x7fff6abd7959 <+89>: vmovups (%rsi), %ymm0
Target 0: (Kernel64Patcher) stopped.
(lldb) frame info
frame #0: 0x00007fff6abd794d libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 77
(lldb) thread backtrace
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10645100c)
  * frame #0: 0x00007fff6abd794d libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 77
    frame #1: 0x00007fff6aa6c6e5 libsystem_c.dylib`__sfvwrite + 402
    frame #2: 0x00007fff6aa6cb4a libsystem_c.dylib`fwrite + 136
    frame #3: 0x0000000100001633 Kernel64Patcher`main(argc=105923928, argv=<unavailable>) at main.cpp:82:5 [opt]
    frame #4: 0x00007fff6a9e1cc9 libdyld.dylib`start + 1
    frame #5: 0x00007fff6a9e1cc9 libdyld.dylib`start + 1
(lldb) thread list
Process 94654 stopped
* thread #1: tid = 0x5805d6, 0x00007fff6abd794d libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 77, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10645100c)
```

**Comment by Ralph0045** [comment]
It should be fixed with the latest version of liboffsetfinder64

**Comment by RedL0tus** [comment]
> It should be fixed with the latest version of liboffsetfinder64

It does not crash after the update, thank you.
