### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by justtryingthingsout** [Ralph0045/Kernel64Patcher#2]
`justtryingthingsout:kernelcache USER$ ./Kernel64Patcher kernelcache.release.iphone7.dec kernelcache.release.iphone7.out 12 -a`

`main: Starting...
libc++abi.dylib: terminating with uncaught exception of type tihmstar::OFexception: std::exception
Abort trap: 6`

**Comment by Ralph0045** [comment]
What version and device is it?
